// Unclogger Prompt Type Actions
export const SHOW_UNCLOGGER_PROMPT_DIALOG = 'SHOW_UNCLOGGER_PROMPT_DIALOG'
export const HIDE_UNCLOGGER_PROMPT_DIALOG = 'HIDE_UNCLOGGER_PROMPT_DIALOG'

// Flag Type Actions
export const SHOW_FLAG_DIALOG = 'SHOW_FLAG_DIALOG'
export const HIDE_FLAG_DIALOG = 'HIDE_FLAG_DIALOG'
